FROM node:18-alpine3.15

WORKDIR /app

RUN apk update && apk upgrade && apk add bash && apk add yarn

COPY ./package.json ./yarn.lock ./

RUN yarn install

COPY . .

# ENV REACT_APP_API_URL=http://localhost:4000/

RUN chmod 777 -R build && chmod 777 -R .next

EXPOSE 3000

CMD ["yarn", "dev"]

