version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile.dev
        container_name: client
        networks:
            - digitaltechnologia
        ports:
            - 3000:3000
            - 443:443
        volumes:
            - ./:/app
            # Ignore the folder that we don't want to mount to the container
            - /app/.next
            - /app/build
            - /app/node_modules
networks:
    digitaltechnologia:
        driver: bridge
