FROM node:18-alpine3.15

WORKDIR /app

RUN apk update && apk upgrade && apk add bash && apk add yarn

COPY ./package.json ./yarn.lock ./

RUN yarn install

# RUN mkdir node_modules/.cache && chmod -R 777 node_modules/.cache

COPY . .

# ENV REACT_APP_API_URL=http://localhost:4000/

EXPOSE 3000

CMD ["yarn", "dev"]
